
---
include:
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: corne_left
  - board: nice_nano_v2
    shield: corne_right
  - board: seeeduino_xiao_ble
    shield: corne_dongle_xiao
    snippet: zmk-usb-logging
  - board: seeeduino_xiao_ble
    shield: settings_reset